import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';

dotenv.config();

async function populateFromOldDB() {
  console.log('🏪 Populating Supabase Store from Old Database...\n');

  const AppDataSource = new DataSource({
    type: 'postgres',
    url: process.env.DATABASE_URL,
    synchronize: false,
    logging: false,
    ssl: {
      rejectUnauthorized: false,
    },
  });

  try {
    await AppDataSource.initialize();
    console.log('✅ Connected to Supabase\n');

    // Clear existing items
    console.log('🗑️ Clearing existing store items...');
    await AppDataSource.query('DELETE FROM store_items');
    console.log('✅ Store cleared\n');

    console.log('📦 Inserting store items from old database...\n');

    // Exact items from your old database (based on screenshots)
    const items = [
      // FUEL ITEMS - Boosts
      {
        itemId: 'profile-boost-1h',
        name: 'Profile Boost (1h)',
        description: 'Boost your profile to 10x more visibility for 1 hour. Be seen by more potential matches!',
        icon: '🚀',
        price: 25,
        currency: 'fuel',
        category: 'boosts',
        type: 'boost',
        subcategory: 'visibility',
        duration: 1,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'profile-boost-6h',
        name: 'Profile Boost (6h)',
        description: 'Extended profile boost for 6 hours. More visibility, more matches!',
        icon: '🚀',
        price: 120,
        currency: 'fuel',
        category: 'boosts',
        type: 'boost',
        subcategory: 'visibility',
        duration: 6,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'super-boost-24h',
        name: 'Super Boost (24h)',
        description: 'Maximum profile boost for 24 hours. Ultimate visibility!',
        icon: '⚡',
        price: 400,
        currency: 'fuel',
        category: 'boosts',
        type: 'boost',
        subcategory: 'visibility',
        duration: 24,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // FUEL ITEMS - Tools
      {
        itemId: 'swipe-rewind-single',
        name: 'Swipe Rewind',
        description: 'Undo your last swipe. Changed your mind? Get a second chance!',
        icon: '↩️',
        price: 15,
        currency: 'fuel',
        category: 'tools',
        type: 'rewind',
        subcategory: 'utility',
        duration: null,
        maxUses: 1,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'swipe-rewind-5pack',
        name: 'Swipe Rewind (5-Pack)',
        description: 'Bundle of 5 swipe rewinds. Better value!',
        icon: '↩️',
        price: 60,
        currency: 'fuel',
        category: 'tools',
        type: 'rewind',
        subcategory: 'utility',
        duration: null,
        maxUses: 5,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // FUEL ITEMS - Super Likes
      {
        itemId: 'super-like-single',
        name: 'Super Like',
        description: 'Show someone you really like them! Stand out from the crowd.',
        icon: '⭐',
        price: 20,
        currency: 'fuel',
        category: 'likes',
        type: 'super_like',
        subcategory: 'engagement',
        duration: null,
        maxUses: 1,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'super-like-5pack',
        name: 'Super Like (5-Pack)',
        description: 'Bundle of 5 super likes. Show your interest!',
        icon: '⭐',
        price: 80,
        currency: 'fuel',
        category: 'likes',
        type: 'super_like',
        subcategory: 'engagement',
        duration: null,
        maxUses: 5,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // PREMIUM ITEMS - Memberships
      {
        itemId: 'premium-membership-permanent',
        name: 'Premium Membership (Permanent)',
        description: 'Unlock ALL premium features FOREVER! Unlimited everything!',
        icon: '👑',
        price: 50,
        currency: 'premium',
        category: 'membership',
        type: 'premium',
        subcategory: 'premium',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'vip-status-permanent',
        name: 'VIP Status (Permanent)',
        description: 'Elite VIP status with exclusive benefits and priority support!',
        icon: '👔',
        price: 100,
        currency: 'premium',
        category: 'membership',
        type: 'vip',
        subcategory: 'vip',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },

      // PREMIUM ITEMS - Swipes
      {
        itemId: 'unlimited-swipes-24h',
        name: 'Unlimited Swipes (24h)',
        description: 'Get unlimited swipes for 24 hours. Swipe as much as you want!',
        icon: '∞',
        price: 4,
        currency: 'premium',
        category: 'matching',
        type: 'tools',
        subcategory: 'tools',
        duration: 24,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'see-who-liked-24h',
        name: 'See Who Liked You (24h)',
        description: 'See who liked your profile for 24 hours. Know who\'s interested!',
        icon: '👀',
        price: 6,
        currency: 'premium',
        category: 'discovery',
        type: 'insight',
        subcategory: 'insight',
        duration: 24,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // PREMIUM ITEMS - Read Receipts
      {
        itemId: 'read-receipts-7days',
        name: 'Read Receipts (7 days)',
        description: 'Know when your messages are read for 7 days!',
        icon: '✓✓',
        price: 8,
        currency: 'premium',
        category: 'messaging',
        type: 'communication',
        subcategory: 'communication',
        duration: 168,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'passport-travel-30days',
        name: 'Passport Travel (30 days)',
        description: 'Change your location to anywhere in the world for 30 days!',
        icon: '🌍',
        price: 15,
        currency: 'premium',
        category: 'location',
        type: 'travel',
        subcategory: 'travel',
        duration: 720,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // PREMIUM ITEMS - Profile Frames (Customization)
      {
        itemId: 'gold-profile-frame',
        name: 'Gold Profile Frame',
        description: 'Elegant golden frame for your profile. Show your premium status!',
        icon: '🖼️',
        price: 12,
        currency: 'premium',
        category: 'customization',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'diamond-profile-frame',
        name: 'Diamond Profile Frame',
        description: 'Ultra-exclusive diamond frame. The ultimate luxury!',
        icon: '💎',
        price: 25,
        currency: 'premium',
        category: 'customization',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'rainbow-profile-frame',
        name: 'Rainbow Profile Frame',
        description: 'Colorful animated rainbow frame. Show your vibrant personality!',
        icon: '🌈',
        price: 18,
        currency: 'premium',
        category: 'customization',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },

      // BUNDLES
      {
        itemId: 'fuel-mega-pack',
        name: 'Fuel Mega Pack',
        description: 'Massive fuel bundle! 3000 Fuel Points at a discount!',
        icon: '🔥',
        price: 0,
        currency: 'usd',
        category: 'bundles',
        type: 'currency',
        subcategory: 'currency',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'premium-mega-pack',
        name: 'Premium Mega Pack',
        description: 'Ultimate premium bundle! 500 Premium Points!',
        icon: '💎',
        price: 0,
        currency: 'usd',
        category: 'bundles',
        type: 'currency',
        subcategory: 'currency',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'ultimate-starter-pack',
        name: 'Ultimate Starter Pack',
        description: 'Everything you need to succeed! Best value for new users!',
        icon: '🎁',
        price: 0,
        currency: 'usd',
        category: 'bundles',
        type: 'special',
        subcategory: 'special',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // PREMIUM BOOST
      {
        itemId: 'spotlight-boost-1h',
        name: 'Spotlight Boost (1h)',
        description: 'Be the featured profile for 1 hour. Maximum exposure!',
        icon: '🔦',
        price: 200,
        currency: 'fuel',
        category: 'boosts',
        type: 'premium',
        subcategory: 'premium',
        duration: 1,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // FUEL ITEMS - Profile Frames
      {
        itemId: 'silver-profile-frame',
        name: 'Silver Profile Frame',
        description: 'A sleek silver frame to highlight your profile!',
        icon: '🥈',
        price: 150,
        currency: 'fuel',
        category: 'customization',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'see-who-liked-1h',
        name: 'See Who Liked You (1h)',
        description: 'Peek at who liked your profile for 1 hour!',
        icon: '👀',
        price: 45,
        currency: 'fuel',
        category: 'discovery',
        type: 'insight',
        subcategory: 'insight',
        duration: 1,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'fire-profile-frame',
        name: 'Fire Profile Frame',
        description: 'A hot fire frame that shows your passion!',
        icon: '🔥',
        price: 200,
        currency: 'fuel',
        category: 'customization',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'unlimited-swipes-1h',
        name: 'Unlimited Swipes (1h)',
        description: 'Swipe without limits for 1 hour. Find your matches faster!',
        icon: '∞',
        price: 25,
        currency: 'fuel',
        category: 'matching',
        type: 'tools',
        subcategory: 'tools',
        duration: 1,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'unlimited-swipes-6h',
        name: 'Unlimited Swipes (6h)',
        description: 'Swipe without limits for 6 hours. Extended swiping session!',
        icon: '∞',
        price: 100,
        currency: 'fuel',
        category: 'matching',
        type: 'tools',
        subcategory: 'tools',
        duration: 6,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'super-like-3pack',
        name: 'Super Like (3-Pack)',
        description: 'Bundle of 3 super likes. Show your interest!',
        icon: '⭐',
        price: 45,
        currency: 'fuel',
        category: 'likes',
        type: 'engagement',
        subcategory: 'engagement',
        duration: null,
        maxUses: 3,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'super-like-10pack',
        name: 'Super Like (10-Pack)',
        description: 'Bundle of 10 super likes. For those who want to make an impact!',
        icon: '⭐',
        price: 140,
        currency: 'fuel',
        category: 'likes',
        type: 'engagement',
        subcategory: 'engagement',
        duration: null,
        maxUses: 10,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'read-receipts-1day',
        name: 'Read Receipts (24h)',
        description: 'See when your messages are read for 24 hours!',
        icon: '✓✓',
        price: 35,
        currency: 'fuel',
        category: 'messaging',
        type: 'communication',
        subcategory: 'communication',
        duration: 24,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },
      {
        itemId: 'bronze-profile-frame',
        name: 'Bronze Profile Frame',
        description: 'A classic bronze frame for your profile!',
        icon: '🥉',
        price: 60,
        currency: 'fuel',
        category: 'customization',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'passport-travel-1day',
        name: 'Passport Travel (24h)',
        description: 'Travel anywhere in the world for 24 hours!',
        icon: '✈️',
        price: 50,
        currency: 'fuel',
        category: 'location',
        type: 'travel',
        subcategory: 'travel',
        duration: 24,
        maxUses: null,
        isActive: true,
        isPermanent: false,
        isLimited: false,
      },

      // MORE PREMIUM FRAMES
      {
        itemId: 'profile_frame_premium_mystic',
        name: 'Mystic Premium Frame',
        description: 'An otherworldly frame with mystical vibes!',
        icon: '🔮',
        price: 15,
        currency: 'premium',
        category: 'customization',
        type: 'profile_frame',
        subcategory: 'profile_frame',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'profile_frame_premium_cosmic',
        name: 'Cosmic Premium Frame',
        description: 'A cosmic frame with swirling galaxy effects!',
        icon: '🌌',
        price: 20,
        currency: 'premium',
        category: 'customization',
        type: 'profile_frame',
        subcategory: 'profile_frame',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'profile_frame_premium_emerald',
        name: 'Emerald Premium Frame',
        description: 'A stunning emerald frame with precious gemstone aesthetics!',
        icon: '💚',
        price: 120,
        currency: 'fuel',
        category: 'customization',
        type: 'profile_frame',
        subcategory: 'profile_frame',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'profile_frame_platinum',
        name: 'Platinum Profile Frame',
        description: 'A sleek platinum frame with metallic shine!',
        icon: '⚪',
        price: 180,
        currency: 'fuel',
        category: 'customization',
        type: 'profile_frame',
        subcategory: 'profile_frame',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'profile_frame_legendary_phoenix',
        name: 'Phoenix Legendary Frame',
        description: 'An epic phoenix frame with animated flames!',
        icon: '🔥',
        price: 300,
        currency: 'fuel',
        category: 'customization',
        type: 'profile_frame',
        subcategory: 'profile_frame',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
      {
        itemId: 'profile_frame_basic',
        name: 'Profile Frame',
        description: 'A customizable profile frame where you can add your own touch!',
        icon: '👑',
        price: 50,
        currency: 'fuel',
        category: 'Profile Enhancement',
        type: 'frames',
        subcategory: 'frames',
        duration: null,
        maxUses: null,
        isActive: true,
        isPermanent: true,
        isLimited: false,
      },
    ];

    let successCount = 0;
    let failCount = 0;

    for (const item of items) {
      try {
        await AppDataSource.query(
          `INSERT INTO store_items (
            "itemId", name, description, icon, price, currency, category, type, 
            subcategory, duration, "maxUses", "isActive", "isPermanent", "isLimited"
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)`,
          [
            item.itemId,
            item.name,
            item.description,
            item.icon,
            item.price,
            item.currency,
            item.category,
            item.type,
            item.subcategory,
            item.duration,
            item.maxUses,
            item.isActive,
            item.isPermanent,
            item.isLimited,
          ],
        );

        successCount++;
        const currencyIcon = item.currency === 'fuel' ? '🔥' : item.currency === 'premium' ? '💎' : '💵';
        console.log(`  ✅ ${item.name} (${item.price} ${currencyIcon})`);
      } catch (error: any) {
        failCount++;
        console.error(`  ❌ Failed to insert ${item.name}:`, error.message);
      }
    }

    console.log(`\n📊 Results:`);
    console.log(`  ✅ Success: ${successCount}`);
    console.log(`  ❌ Failed: ${failCount}`);
    console.log(`  📦 Total: ${items.length}\n`);

    // Verify counts by category
    const fuelItems = await AppDataSource.query(
      `SELECT COUNT(*) as count FROM store_items WHERE currency = 'fuel'`,
    );
    const premiumItems = await AppDataSource.query(
      `SELECT COUNT(*) as count FROM store_items WHERE currency = 'premium'`,
    );
    const usdItems = await AppDataSource.query(
      `SELECT COUNT(*) as count FROM store_items WHERE currency = 'usd'`,
    );

    console.log(`🔥 Fuel items: ${fuelItems[0].count}`);
    console.log(`💎 Premium items: ${premiumItems[0].count}`);
    console.log(`💵 USD items: ${usdItems[0].count}\n`);

    await AppDataSource.destroy();
    console.log('✅ Store populated successfully!\n');
  } catch (error) {
    console.error('❌ Error:', error);
    throw error;
  }
}

populateFromOldDB()
  .then(() => {
    console.log('🎯 Done! Store is ready with all original items.');
    process.exit(0);
  })
  .catch(() => process.exit(1));
